### ISSUE TITLE
Allow preserving rawMode in stdin after unmount

### ISSUE THREAD

**Issue by danikaze** [vadimdemedes/ink-text-input#29]
Not all applications finish when this component is not rendered, and some applications are managed in rawMode independently of ink.
Adding this prop will allow to properly use this component with this type of applications.

**Comment by vadimdemedes** [comment]
There's no need for this functionality in this component, because Ink takes care of this for you. If you enable raw mode yourself via [`setRawMode()`](https://github.com/vadimdemedes/ink#setrawmode), Ink will not disable it after text input is unmounted. Ink keeps track how many times raw mode was requested and will only disable it when "no one else" needs it.
